### ISSUE TITLE
SP Racing H7 Zero current meter

### ISSUE THREAD

**Issue by Peppe911** [spracing/betaflight#11]
Hi.
I'm trying to get support for this issue, but in betaflight forum he close the issue cause i have to contact the board productor, so this is the problem:
New board , bought directly from @hydra shop, tested with only battery voltage wire from 4in1 esc, motors wire and current sensor wire.
No short circuits on the board.
ESC is HAKRC E50AX4, no issues reading current from this board with omnibus F4 V3

Voltage meter is ok.
Current meter is impossible to set.
When i measure ADC pad 2, in idle condition and when disconnected from the wire, i read about 800mv; total idle current from battery is less than 130mA.
When i connect the current sensor wire from ESC this voltage drops to about 250mv;
if i measure directly from this pad, with current sensor connected and with various loads, this voltage don't change.
If i measure directly esc current output, without connecting the wire to the FC, i read 0mv in idle, 30mv at 1.36A (4 motors at 1100) and 70mv at 2.64A (4 motors at 1150).

So i think someting is wrong in settings, or is broken in the FC or is a firmware bug.

I try also inverting resources from 
resource ADC_CURR 1 C01
resource ADC_EXT 1 C05
to
resource ADC_CURR 1 C05
resource ADC_EXT 1 C01
ADC2 PAD still in this condition.

[spracing cli dump.txt](https://github.com/spracing/betaflight/files/5327024/spracing.cli.dump.txt)

**Comment by hydra** [comment]
As per email conversation:

The ADC inputs float when not connected, so a reading of 800mv is not unexpected, the float voltage also depends on the usage of other ADC pins.

There are NO components between the FC and the current sensor pad on the H7NANO and H7ZERO, just a PCB trace from the MCU to the ADC pads.

You can test the hardware as follows:
1. Reset the FC to defaults (via `defaults` command in CLI).
2. Connect a battery to the FC, without a battery BF will show no current usage.
3. Connect the current sensor pad to GROUND,  in the software it should read a very low current draw.
4. Disconnect the sensor pad from GROUND.
5. Use a 10k resistor and connect the current sensor pad to 3.3V pad on the FC.  In the software it should read a very high current draw.
6. Disconnect the sensor pad from 3.3V when you are finished.

If these tests perform as expected then the FC hardware is working as intended and test results and bug reports should be posted on the BF issue tracker, referencing this issue as appropriate.

Additionally, in BF there as an ADC DEBUG mode which allows you to see the raw ADC channel values for each enabled ADC pin.

**Comment by hydra** [comment]
@Peppe911 reported the following results via email:

```
3.	With “1” in the current scale field, with zero offset, current is 0; as i understand, lower scale value -> higher current measured 
4.	Ok
5.	With 1000 in scale value , in idle i read 10 amps, with current pad shorted to 3.3v with the resistor i read 32.7 amps, that is a big increase with this scale. 
6.	Ok
```

Requested @Peppe911 to reset the FC to defaults, leave the current sensor configuration alone and re-test.  Don't adjust the scale and offset value when testing, the default is fine.

**Comment by Peppe911** [comment]
As soon as possible i'll try, meanwhile i'm waiting for a better current meter for double check the real drain from battery.
regards
